### ISSUE TITLE
lightning talks

### ISSUE THREAD

**Issue by afeld** [18F/ideas#1]
This idea is not originally mine, and has come up a bunch of times. My team at American Express used to do them every week as a brownbag lunch, and they were a blast. Some were highly technical, but they ran the gamut...my talk I was proudest of was about [a Brazilian economic policy from the 90's](http://www.scribd.com/doc/46086444/Plano-Real-How-Fake-Money-Saved-Brazil). I would love to hear about:
- What other people in 18F are working on
- Some new tool that someone discovered/tried
- The tech/thinking/approach behind an 18F project
- Some open source library someone created or contributed to
- What someone learned from an interesting article, event, online discussion, etc.
- Talking through some current event
- Some interesting side project someone's working on
- A test run of a talk someone is going to do at a meetup/conference

Some open questions:
- How work-related do the topics need to be?
- How often should they be?
- How long should they be? (I'm thinking 15 min talk, 15 min Q&A)
- What day/time should they be? (I'm thinking Fridays)
- Can we make these open to other govvies (or even the public) to join?

Would love feedback and gauge interest – happy to do the actual wrangling of lining up speakers, getting rooms reserved, and getting it on the calendar.

**Comment by bsweger** [comment]
Yes to all of this--would definitely participate as an attendee and a speaker. Other topic suggestions:
- There's been some recent chatter around the need to highlight things that didn't go well and share what was learned. 
- Tales of ye olde 18F lore. For example, the story that @aaronsnow shared via e-mail this week was so interesting; for newer team members it's great to know about the work done by those before us.

**Comment by mbland** [comment]
@RobertLRead had proposed starting a YouTube channel for PIFs. We should capture as many of these to post on YouTube as possible and surface them in the Hub as well. It'd also be nice to surface the talks that 18F members give outside of the organization; though it's a different spirit than what's proposed here, the publishing implementation may overlap.

I would suggest, though, @afeld, that you wrangle at least one co-organizer to help you with this. I'm happy to help however I can, but am not sure I could personally commit right now. But talking I can do anytime.

**Comment by arlusk** [comment]
We do these at Threespot too--they're called Sharespots here. Some have a shorter format, like a 5-10 minute [Ignite](http://en.wikipedia.org/wiki/Ignite_%28event%29) round of mini-talks. Some have a longer format, up to an hour. They range from things that are professionally interesting (UX for the Aging) to ones that are more personally developmental (how to make kombucha tea at home). They're a very welcome part of our work culture.

**Comment by jpyuda** [comment]
I'd love to leverage the folks we have at 18F as speakers/people for the rest of us to learn from more often.

We did lightning talks of a couple different sorts at CFPB regularly (and I think they still do them). A similar concept at 18F would be very welcome.

cc: @khandelwal

**Comment by kaitlin** [comment]
I would love it if the engineering teams could do this, potentially as pilot, or just individually if it proves too annoying to handle the whole team at once on a remote call. cc @theresaanna @jgrevich @sashax @micahsaul

**Comment by theresaanna** [comment]
@kaitlin Our team has started doing demos. We've only done one so far, but it ended up being quick (no more than 10 minutes or so), so maybe that pilot is already in progress! @seanherron took us through Peace Corps devops tools and setup.

Maybe the smaller teams could serve as a launch pad for talks to be given on a larger scale? Folks could try their talk out for the smaller audience and see if they want to participate in a less frequent engineering- or org-wide session.

As @jpyuda said, we did lightning talks at our in-person all hands at CFPB and they were usually the highlight of the week. Doing them in person is pretty fun and makes the experience of an all hands feel a bit more well-rounded re: it not just being leadership who is up on stage talking. I think we should plan to give it a try at the next in person all-hands as well.

cc: @jgrevich @sashax @micahsaul

**Comment by cmc333333** [comment]
:+1: CFPB routinely held a few types of talks. At regroups, we had lightening talks (10 minutes or less) which were both fun and often about our internal culture. They sometimes covered technical stuff, but, given the format, tended to be a step more abstract.

There were a set of technical demos every other week (roughly an hour, sometimes two, with both internal speakers and the occasional external person.) These were generally deeper into the weeds, but they also offered a forum for feedback of deep topics. In some ways, these balanced more administrivia-centric meetings for the same group of people.

@jehlers and others also organized a third category of project-specific talks aimed at _non_ technical folks. The idea was to show the rest of the bureau what we were working on; iirc, individuals outside of the tech department were targeted to attend. Generally each talk was about 20 minutes, but there'd be 3-5 per meeting.

All of these were valuable for different reasons. The lightening talk format was particularly good during regroups as it was the most social. I would recommend starting up something like the second category to share across project groups. Also lean on Jen; she has ways to make people present :)

**Comment by konklone** [comment]
What a great first idea this is! I am addicted to attending and delivering lightning talks. Lightning talks forever.

**Comment by quepol** [comment]
Just discovering this... <3

I would love to have a section of the upcoming offsite dedicated to this. At YxYY001 attendees did a whole afternoon of "5-minute Primers" ranging from the creation of the universe to the proper way to give CPR. Having a couple hours blocked off for this plus socializing would be _awesome_.

**Comment by afeld** [comment]
[Now a thing!](https://github.com/18F/tech-talks)
