### ISSUE TITLE
have a place for real-time conversations w/ outside contributors

### ISSUE THREAD

**Issue by afeld** [18F/ideas#5]
...or people that are interested in doing so, e.g.
- IRC
- Slack
- Gitter

**Comment by afeld** [comment]
CC:
- https://18f.slack.com/archives/wg-devcommunity/p1426789540000029
- https://18f.slack.com/archives/admins-slack/p1426789551000363

@NoahKunin @gbinal @quepol @ultrasaurus @melodykramer

**Comment by melodykramer** [comment]
Agreed!

**Comment by bsweger** [comment]
YES!

**Comment by quepol** [comment]
+1 just gotta figure out where/how to do it.

**Comment by afeld** [comment]
See http://rauchg.com/slackin/ for how we could make Slack work.

**Comment by NoahKunin** [comment]
Holy moooooooooooly

Let's get this thing done. Whoever wants to work it out with me, fine some
time on my calendar

On Thursday, April 9, 2015, Aidan Feldman notifications@github.com wrote:

> See http://rauchg.com/slackin/ for how we could make Slack work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/ideas/issues/5#issuecomment-91362560.

## 

Noah Kunin
Delivery Architecture + Infrastructure Services Director
202-577-7167 | @18F https://twitter.com/18F

**Comment by NoahKunin** [comment]
Just reviewed documentation, also supports single channel mode!

On Thursday, April 9, 2015, Noah Kunin noah.kunin@gsa.gov wrote:

> Holy moooooooooooly
> 
> Let's get this thing done. Whoever wants to work it out with me, fine some
> time on my calendar
> 
> On Thursday, April 9, 2015, Aidan Feldman <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > See http://rauchg.com/slackin/ for how we could make Slack work.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/18F/ideas/issues/5#issuecomment-91362560.
> 
> ## 
> 
> Noah Kunin
> Delivery Architecture + Infrastructure Services Director
> 202-577-7167 | @18F https://twitter.com/18F

## 

Noah Kunin
Delivery Architecture + Infrastructure Services Director
202-577-7167 | @18F https://twitter.com/18F

**Comment by ultrasaurus** [comment]
this would be awesome!

**Comment by NoahKunin** [comment]
Yeah, I want to fast track this.

On Thu, Apr 9, 2015 at 8:29 PM, Sarah Allen notifications@github.com
wrote:

> this would be awesome!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/ideas/issues/5#issuecomment-91387983.

## 

Noah Kunin
Delivery Architecture + Infrastructure Services Director
202-577-7167 | @18F https://twitter.com/18F

**Comment by afeld** [comment]
Scheduled a chat at 3:30pm EDT tomorrow. Let me know if you'd like an invite, and/or post concerns/questions here.

**Comment by NoahKunin** [comment]
Approved!

**Comment by afeld** [comment]
[Slackin](http://rauchg.com/slackin/) (or [similar](https://github.com/seapy/slack_invite_automation_sinatra)) tally ho!
- [ ] ~~Figure out how users pick the channel they join (will probably require a fork)~~
- [ ] ~~Look into the experience of a single-user guest trying to join an additional channel~~
- [x] Deploy to CF
- [x] Use appropriate billing

**Comment by afeld** [comment]
:tada: https://chat.18f.gov/ :tada: Just works for a single channel at the moment (#midas-public, since @ultrasaurus seems most eager for it). Working in this fork:

https://github.com/18F/slackin

Hub isn't deployed to Cloud Foundry...any suggestions about which org+space to use?

**Comment by NoahKunin** [comment]
@ozzyjohnson @dlapiduz will need to weigh in. Slackin should be in an org/space that essentially bills to my LOB (equivalent to the `DevOps` or `paas` tags in AWS).

**Comment by dlapiduz** [comment]
@afeld `18f/chat`?

**Comment by ultrasaurus** [comment]
@NoahKunin @afeld thank you SO much for this.  We have an outside contributor who is building a major feature (after maybe a dozen small bug fixes) and this totally saves my almost daily communciation to the dev team across email, gchat, slack and text messages.  Also, we can now welcome other prospective or less frequent contributors practively -- increasing transparency, and (I hope) increasing contributions as well.  

Very high impact work!

**Comment by afeld** [comment]
Good to go! If any other projects want channels, let me know.

**Comment by patricknowlan** [comment]
@afeld on the topic of allowing public users access to multiple channels... what if 18f created a second slack/slackin that was public.  Everyone could openly chat about things that span across multiple projects or organizations... tech, design, design patterns.

**Comment by afeld** [comment]
@patricknowlan Wish we could. See https://github.com/18F/slackin/issues/4#issuecomment-118232324.

**Comment by patricknowlan** [comment]
@afeld I think we are on the same page regarding [18F/slackin#4](https://github.com/18F/slackin/issues/4#issuecomment-118232324). I have the same issue with my companies slack.

The slackin readme has a [workaround note](https://github.com/rauchg/slackin#server) which says:

> Important: if you use Slackin in single-channel mode, you'll only be able to invite as many external accounts as paying members you have times 5. If you are not getting invite emails, this might be the reason. Workaround: sign up for a free org, and set up Slackin to point to it (all channels will be visible).

Which made me think, what if 18f had two slack subdomains, **18f.slack.com** (paid account) and **openGov.slack.com**(free account). 

openGov would have unlimited public channels for topics broader than a single project... SSL / Open Data / API Standards ... similar to what [scotch.io does for angular.](https://scotch-slack.herokuapp.com/)

**Comment by afeld** [comment]
Right...what I'm saying is that a separate (fully open) Slack domain could not currently be operated by 18F.
