### ISSUE TITLE
plugin for warning about links to private pages

### ISSUE THREAD

**Issue by afeld** [18F/ideas#8]
Across our various documentation sites (the Hub, the [Product Guide](https://github.com/18F/product-guide), etc.), we have a mix of content where most of the page can be public, but certain links aren't publicly accessible: Google Docs, private repositories, etc. In the Product Guide, for example, we are using a private repository so that we can have sentences with these private links excluded from the public build.

Since access control is done on the destination side (at the repository level, or in Google Docs), I propose that we make our lives easier by:
- Not worrying about excluding these sentences/links from public builds
- Using a Jekyll/JavaScript plugin with a blacklist of domains/URLs, that does some combination of the following to each private link:
  - Makes them a different color
  - Adds a :lock: icon
  - Adds a tooltip explaining that it may not work for non-18F staff

/cc @mbland

**Comment by afeld** [comment]
P.S. I have some time on a plane this evening so might start hacking on it, unless people think it's a terrible approach.

**Comment by hollyallen** [comment]
Also Mike instituted this for us: https://github.com/18F/pages-server/blob/master/README.md#publishing-to-internal-and-external-sites-from-the-same-branch

**Comment by annahsgraves** [comment]
Thanks @afeld. Who can help me with that plugin you reference? After a recent review, I found that the links may end up being the only thing that is NOT public, so would be great to have help with this plugin as we are about to make the repo public. It's a nice-to-have.

CC: @hollyallen

**Comment by afeld** [comment]
https://github.com/18F/private-eye :tada: 

@annahsebok Catch me in Slack if you'd like help with it, or I'm happy to set it up on any site you like.

**Comment by annahsgraves** [comment]
:+1: @afeld. I think we're good on this for now (ie - not needed)
